# Generated by Django 5.2.11 on 2026-02-16 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='csv_uploads/')),
                ('columns', models.JSONField(default=list, help_text='List of column names')),
                ('row_count', models.IntegerField(default=0)),
                ('preview_data', models.JSONField(default=list, help_text='First 100 rows as list of dicts')),
                ('column_stats', models.JSONField(default=dict, help_text='Basic stats per column')),
                ('insights', models.TextField(blank=True, default='')),
                ('follow_up_answers', models.JSONField(default=list, help_text='List of follow-up Q&A pairs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CSV Report',
                'verbose_name_plural': 'CSV Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
